<?php

namespace AtsBundle\Repository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * findRecordsByFilter
     * @param $filter
     * @param string $sort
     * @param string $orderBy
     * @param bool $paginator
     * @return array
     */
    public function findRecordsByFilter($filter, $sort = 'id', $orderBy = 'DESC', $paginator = false)
    {

        $queryBuilder = $this->createQueryBuilder('s');
        $queryBuilder->select('s');

        if ((isset($filter['title']) && !is_null($filter['title']))) {
            $queryBuilder->andWhere('s.title  LIKE :title')->setParameter('title', '%' . $filter['title'] . '%');
        }
        $queryBuilder->orderBy('s.'.$sort, $orderBy);

        if($paginator == false){
            $result =  $queryBuilder->getQuery()->getResult();
        }else{
            $result =  $queryBuilder->getQuery();
        }

        return ['total_result' => count($queryBuilder->getQuery()->getResult()) , 'result' => $result];
    }
}
